#!/usr/bin/env bash
# Generate a .env file with the RunSession-triage connection vars by reading
# the test cluster's Kubernetes secrets. Secrets only ever land in the output
# file (chmod 600); this script prints variable NAMES and lengths only.
#
# Usage:
#   ./gen_env.sh                       # writes .env.local (used by run_local.sh)
#   ./gen_env.sh w-test-secrets.env    # writes a clean file to copy into the
#                                      #   w-test workspace secrets UI
#   ./gen_env.sh <out> <kube-context>  # override the kube context
#
# The 6 connection vars map 1:1 to the w-test workspace secrets you must add:
#   TEST_PG_CORE_USER / TEST_PG_CORE_PASSWORD       (core-pguser-core)
#   TEST_PG_USEARCH_USER / TEST_PG_USEARCH_PASSWORD (core-pguser-usearch)
#   TEST_REDIS_PASSWORD                             (redis-sentinel)
#   TEST_NEO4J_PASSWORD                             (neo4j-auth, part after neo4j/)
set -euo pipefail
cd "$(dirname "$0")"

OUT="${1:-.env.local}"
CTX="${2:-gke_runwhen-nonprod-test_northamerica-northeast1_platform-cluster-01}"
NS="${RWTEST_NS:-backend-services}"

command -v kubectl >/dev/null || { echo "ERROR: kubectl not found"; exit 1; }
if ! kubectl --context "$CTX" -n "$NS" get ns "$NS" >/dev/null 2>&1; then
  echo "ERROR: cannot reach namespace '$NS' via context '$CTX'."
  echo "       Check: kubectl config get-contexts"
  exit 1
fi

gs() { # secret, key  -> decoded value (stderr stays quiet)
  kubectl --context "$CTX" -n "$NS" get secret "$1" \
    -o "jsonpath={.data.$2}" 2>/dev/null | base64 -d
}

umask 077
tmp="$(mktemp)"
{
  echo "# generated by gen_env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# context=$CTX ns=$NS — DO NOT COMMIT"
  printf 'export KUBE_CONTEXT=%q\n'              "$CTX"
  printf 'export kubeconfig=%q\n'                "$HOME/.kube/config"
  printf 'export TEST_PG_CORE_USER=%q\n'         "$(gs core-pguser-core user)"
  printf 'export TEST_PG_CORE_PASSWORD=%q\n'     "$(gs core-pguser-core password)"
  printf 'export TEST_PG_USEARCH_USER=%q\n'      "$(gs core-pguser-usearch user)"
  printf 'export TEST_PG_USEARCH_PASSWORD=%q\n'  "$(gs core-pguser-usearch password)"
  printf 'export TEST_REDIS_PASSWORD=%q\n'       "$(gs redis-sentinel redis-password)"
  NEOA="$(gs neo4j-auth NEO4J_AUTH)"
  printf 'export TEST_NEO4J_PASSWORD=%q\n'       "${NEOA#*/}"
} > "$tmp"
mv "$tmp" "$OUT"
chmod 600 "$OUT"

# Also emit a RAW key=value file (no shell escaping, no `export`) for pasting
# the 6 connection values into the w-test workspace-secret UI. printf %q above
# is required for `source`-ing locally but corrupts values with special chars
# when pasted into a non-shell secret store.
RAW="${OUT%.env}.values"; [ "$RAW" = "$OUT" ] && RAW="$OUT.values"
tmp2="$(mktemp)"
{
  echo "# RAW values for the w-test workspace secrets — paste EXACTLY, no quotes"
  printf 'TEST_PG_CORE_USER=%s\n'        "$(gs core-pguser-core user)"
  printf 'TEST_PG_CORE_PASSWORD=%s\n'    "$(gs core-pguser-core password)"
  printf 'TEST_PG_USEARCH_USER=%s\n'     "$(gs core-pguser-usearch user)"
  printf 'TEST_PG_USEARCH_PASSWORD=%s\n' "$(gs core-pguser-usearch password)"
  printf 'TEST_REDIS_PASSWORD=%s\n'      "$(gs redis-sentinel redis-password)"
  NEOA2="$(gs neo4j-auth NEO4J_AUTH)"
  printf 'TEST_NEO4J_PASSWORD=%s\n'      "${NEOA2#*/}"
} > "$tmp2"
mv "$tmp2" "$RAW"
chmod 600 "$RAW"
echo "Also wrote $RAW (chmod 600) — RAW values for the workspace-secret UI."

echo "Wrote $OUT (chmod 600). Variable lengths (values not shown):"
# shellcheck disable=SC1090
set -a; . "./$OUT"; set +a
for v in KUBE_CONTEXT kubeconfig TEST_PG_CORE_USER TEST_PG_CORE_PASSWORD \
         TEST_PG_USEARCH_USER TEST_PG_USEARCH_PASSWORD TEST_REDIS_PASSWORD \
         TEST_NEO4J_PASSWORD; do
  eval "val=\${$v:-}"
  if [ -z "$val" ]; then echo "  $v: MISSING (secret read failed)"; \
  else echo "  $v: len=${#val}"; fi
done
echo "Done. For w-test: copy the TEST_* lines' values into the workspace secrets."
